spring.application.name=janki

# Server Configuration
server.port=8080

# SQLite DataSource Configuration
spring.datasource.url=jdbc:sqlite:janki.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Schema Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Spring Data JDBC
spring.data.jdbc.repositories.enabled=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.data.jdbc=DEBUG
logging.level.com.prairiegrade.janki=DEBUG

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
